### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by sirvon** [startupthekid/CoordinatorKit#13]
Is there any working example of this rendition of the pattern available ?

thank you.

**Comment by thebarndog** [comment]
@sirvon do you mean an app that's open source that uses this library?

**Comment by thebarndog** [comment]
@sirvon if you're asking for a demo, I was actually thinking of deprecating this library or at least performing major revamps. I can put a code example in the next version update if that'd be helpful

**Comment by thebarndog** [comment]
@sirvon if you need examples, I'm happy to provide. I'm in the process of revamping this library after many years.
